### ISSUE TITLE
question about Checkpoint file

### ISSUE THREAD

**Issue by Helenailse1** [idiap/multimodal_gaze_target_prediction#1]
Hello, I really like your paper. Where can I download the faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth and hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth mentioned in the modality_extraction.md?
 I can't find the download link, can you please provide it?

**Comment by SAMY-ER** [comment]
Hi there. Here are the links:

- faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth: [link](http://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth)
- hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth: [link](https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth)

PS: You don't have to use those specific models. You can browse other, potentially better performing, options available in openmmlab (both for detection in the mmdetection package, and pose estimation in the mmpose package). All you'd have to do is download the new checkpoints and use the proper config files for them.
